# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mileone

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_4cdcef58e9ab489aac7d8f3a64177474 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6e52ca9292be4345b5e16042952fd366 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_4cdcef58e9ab489aac7d8f3a64177474 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mileone'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_20d4ef54b98c472da2357c146e96bfa9 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_4cdcef58e9ab489aac7d8f3a64177474 }}/appsvc/staticsite:${{ github.sha }}'